In [1]:
# Must see the link below
# https://laempy.github.io/pyoints/tutorials/icp.html
# new

In [2]:
import simpleicp


In [3]:
import open3d as o3d
import numpy as np
import copy

import csv
import numpy as np
import simpleicp


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [4]:


def read_xyz(path_to_pc):
    X = []
    with open(path_to_pc) as f:
        reader = csv.reader(f, delimiter=' ')
        for row in reader:
            X.append(list(map(float, row)))
    return X


path_to_pc1 = 'D:/image_processing/Michael_CAD/CompareCADandME4/AlignedMicroEpsilon.txt'
path_to_pc2 = 'D:\image_processing\Michael_CAD\RotateCadFiles\90rotatedMicroEpsilon.txt'


X_fix = np.array(read_xyz(path_to_pc1))
X_mov = np.array(read_xyz(path_to_pc2))
#print(path_to_pc1)
#print(path_to_pc2)

#simpleicp.simpleicp(X_fix, X_mov)

In [5]:
transformation=simpleicp.simpleicp(X_fix, X_mov,min_planarity= -0.000001,min_change=0.000000000001,max_iterations=100 )

[02:56:04.473] Create point cloud objects ...
[02:56:04.473] Select points for correspondences in fixed point cloud ...
[02:56:04.476] Estimate normals of selected points ...
[02:56:04.615] Start iterations ...


D:\image_processing\Michael_CAD\3dpointcompare\Step3\simpleicp.py:65: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x, _, _, _ = np.linalg.lstsq(A, l)


[02:56:04.693] Iteration | correspondences | mean(residuals) | std(residuals) 
[02:56:04.693]         0 |            1000 |          0.0557 |          0.8006
[02:56:04.693]         1 |            1000 |          0.0022 |          0.2352
[02:56:04.746]         2 |            1000 |          0.0012 |          0.0421
[02:56:04.825]         3 |            1000 |         -0.0005 |          0.0168
[02:56:04.894]         4 |            1000 |         -0.0002 |          0.0168
[02:56:04.966]         5 |            1000 |         -0.0003 |          0.0168
[02:56:05.026]         6 |            1000 |         -0.0003 |          0.0167
[02:56:05.095]         7 |            1000 |         -0.0003 |          0.0167
[02:56:05.169]         8 |            1000 |         -0.0003 |          0.0167
[02:56:05.226]         9 |            1000 |         -0.0003 |          0.0167
[02:56:05.295]        10 |            1000 |         -0.0003 |          0.0167
[02:56:05.372]        11 |            1000 |        

In [6]:
## Current 
transformation

array([[ 0.9979949 , -0.105417  , -0.03445337, -0.02847946],
       [ 0.1053589 ,  0.99800542,  0.00298343, -0.08089844],
       [ 0.03446508, -0.00381329,  1.00000784,  0.00281015],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
# Reference

transformation

###  Yellow dkhna or save krna hai

In [14]:

import open3d as o3d
import numpy as np
import copy
def draw_registration_result(source, target, transformation):
    source_temp = copy.deepcopy(source)
    target_temp = copy.deepcopy(target)
    source_temp.paint_uniform_color([1, 0.7, 0])
    target_temp.paint_uniform_color([0, 0.651, 0.929])
    target_temp.transform(transformation)
    
    o3d.visualization.draw_geometries([source_temp, target_temp])
    #o3d.visualization.draw_geometries(source_temp)
    #print(source_temp.transform(transformation))

    #o3d.io.write_point_cloud("reg_source1.pcd", source_temp.transform(transformation)) 
    #o3d.io.write_point_cloud("D:/image_processing/Michael_CAD/RotateCadFiles/trasnformed.pcd", target_temp) 
    


In [15]:
source = o3d.io.read_point_cloud( 'D:/image_processing/Michael_CAD/CompareCADandME4/AlignedMicroEpsilon.pcd')
#target = o3d.io.read_point_cloud('../../data3/Mesh2_ROI.pcd')
target = o3d.io.read_point_cloud('D:/image_processing/Michael_CAD/CompareCADandME4/90rotateMicroEpsilon.pcd')
threshold = 0.02
trans_init = np.array([[ 0.9979949 , -0.105417  , -0.03445337, -0.02847946],
       [ 0.1053589 ,  0.99800542,  0.00298343, -0.08089844],
       [ 0.03446508, -0.00381329,  1.00000784,  0.00281015],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

draw_registration_result(source, target, trans_init)



In [ ]:
array([[ 0.9979949 , -0.105417  , -0.03445337, -0.02847946],
       [ 0.1053589 ,  0.99800542,  0.00298343, -0.08089844],
       [ 0.03446508, -0.00381329,  1.00000784,  0.00281015],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
############ Program Ends #######################

In [ ]:
 [[ 8.43603733e-01 -6.62441400e-03  5.36925376e-01 -5.20454077e-02]
 [ 5.93933390e-03  9.99977845e-01  3.00567464e-03 -2.50621039e-04]
 [-5.36933391e-01  6.53380737e-04  8.43624387e-01 -1.20482563e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

In [ ]:
source = o3d.io.read_point_cloud( '../microepsilon/Data2/me_data2.pcd')
#target = o3d.io.read_point_cloud( '../bunny_data/bun45.pcd')
                                   
#o3d.visualization.draw_geometries([source, target])
o3d.visualization.draw_geometries([source])                                   