In [ ]:
# https://stackoverflow.com/questions/57680204/how-to-write-data-from-a-point-cloud-file-to-a-text-file

In [2]:
pwd

'D:\\image_processing\\Michael_CAD\\RotatingPointCloud'

In [5]:
import numpy as np
import open3d as o3d

pcd= o3d.io.read_point_cloud("Files/MicroEpsilon.pcd")
array=np.asarray(pcd.points)


In [6]:
np.savetxt('Files/source.txt', array, delimiter=" ", fmt="%s") 

In [6]:
import pandas as pd

df= pd.read_csv(r"textfile/plane_blade.txt", header=None, sep=" ")

In [7]:
df.head()
len(df)

15090

In [10]:
df

0          1           2
0      8.435681 -11.047253  244.750290
1      8.446041 -11.026495  244.748108
2      8.476759 -10.750369  244.646225
3      8.465103 -10.767718  244.659836
4      8.720955 -10.878760  244.621460
...         ...        ...         ...
15085 -4.601030   1.012755  218.866974
15086 -4.917066   0.879322  218.440002
15087 -4.937317   0.644614  218.617661
15088 -5.004478   0.707482  218.440002
15089 -4.782608   0.777313  218.753815

[15090 rows x 3 columns]

In [8]:
import pandas as pd

df1= pd.read_csv(r"textfile/rotated_blade.txt", header=None, sep=" ")
len(df1)

15090

In [9]:
df1

0           1           2
0      8.435681 -127.034416  209.492251
1      8.446041 -127.015153  209.500288
2      8.476759 -126.723985  209.543259
3      8.465103 -126.745735  209.546886
4      8.720955 -126.824786  209.459972
...         ...         ...         ...
15085 -4.601030 -104.041641  192.559380
15086 -4.917066 -103.954038  192.120706
15087 -4.937317 -104.245188  192.164091
15088 -5.004478 -104.104842  192.038322
15089 -4.782608 -104.194009  192.347197

[15090 rows x 3 columns]

In [115]:
df1

0          1           2
0      210.508086 -11.047253  125.140765
1      210.511847 -11.026495  125.130869
2      210.442712 -10.750369  125.049973
3      210.447868 -10.767718  125.067135
4      210.553813 -10.878760  124.831108
...           ...        ...         ...
15085  181.684261   1.012755  122.125964
15086  181.154222   0.879322  122.161205
15087  181.292774   0.644614  122.274235
15088  181.106993   0.707482  122.234760
15089  181.490934   0.777313  122.217616

[15090 rows x 3 columns]

In [62]:
array

array([[  8.43568134, -11.04725266, 244.75028992],
       [  8.44604111, -11.02649498, 244.74810791],
       [  8.47675896, -10.75036907, 244.64622498],
       ...,
       [ -4.93731689,   0.6446135 , 218.61766052],
       [ -5.00447845,   0.70748168, 218.44000244],
       [ -4.78260803,   0.77731293, 218.7538147 ]])

In [66]:
type(array[0][0])

numpy.float64

In [ ]:
#

In [81]:
######################

def read_xyz(path_to_pc):
    X = []
    with open(path_to_pc) as f:
        reader = csv.reader(f, delimiter=' ')
        for row in reader:
            X.append(list(map(float, row)))
    return X


path_to_pc1 = 'converted/Rotated2_FW75735.txt'


X_fix = np.array(read_xyz(path_to_pc1))
#
#############################

In [82]:
X_fix

array([[   8.43568134, -127.03441585,  209.49225139],
       [   8.44604111, -127.01515317,  209.50028826],
       [   8.47675896, -126.72398461,  209.54325939],
       ...,
       [  -4.93731689, -104.24518807,  192.16409077],
       [  -5.00447845, -104.10484224,  192.03832175],
       [  -4.78260803, -104.19400916,  192.3471968 ]])

In [74]:


path_to_pc2 = '../../../data/dragon1.xyz'


X_mov = np.array(read_xyz(path_to_pc2))


In [75]:
X_mov

array([[ 3.1798,  5.0338,  5.6575],
       [ 3.2396,  5.0338,  5.6575],
       [ 3.2727,  5.0359,  5.6925],
       ...,
       [ 4.3913, -2.0228,  7.9938],
       [ 4.3637, -2.028 ,  7.9399],
       [ 4.377 , -2.0292,  7.9644]])

In [108]:
######### Viewer


if __name__ == "__main__":
    knot_data = o3d.data.KnotMesh()
    #print(f"Reading mesh from file: knot.ply stored at {knot_data.path}")
    mesh = o3d.io.read_triangle_mesh("../Step1/Files_blades/Rotatey.ply")
    R = mesh.get_rotation_matrix_from_yxz((1,0,0))
    mesh = mesh.rotate(R, center=(0,0,0))
    mesh.compute_vertex_normals()
    o3d.visualization.draw_geometries([mesh])



###############